management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxRetryAttempts: 3
        waitDuration: 5s

  ratelimiter:
    instances:
      getOrdersRate:
        limitForPeriod: 1
        limitRefreshPeriod: 5s
        timeoutDuration: 1s

  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true #Expose circuit breaker health via the actuator
        slidingWindowSize: 10 #Size of the sliding window for call recording
        slidingWindowType: COUNT_BASED #Use count based sliding window
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
